apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  replicas: 1
  selector:
      matchLabels:
        app: ubuntu   
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: different-service
        image: payalsasmal/ubuntu:latest
        imagePullPolicy: Always
        command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
        ports:
        - containerPort: 4000
          name: ubuntu

---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  ports:
    - port: 4000
      targetPort: 4000
  selector:
      app: ubuntu
  type: LoadBalancer
