apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu_18.04
  labels:
    app: ubuntu_18.04
spec:
  replicas: 1
  selector:
      matchLabels:
        app: ubuntu_18.04
  template:
    metadata:
      labels:
        app: ubuntu_18.04
    spec:
      containers:
      - name: different-service
        image: payalsasmal/ubuntu_18.04:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
          name: ubuntu_18.04

---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu_18.04
  labels:
    app: ubuntu_18.04
spec:
  ports:
    - port: 4000
      targetPort: 4000
  selector:
      app: ubuntu_18.04
  type: LoadBalancer
