apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deploy
  labels:
    app: ubuntu-deploy
spec:
  replicas: 1
  selector:
      matchLabels:
        app: ubuntu-pod
  template:
    metadata:
      labels:
        app: ubuntu-pod
    spec:
      containers:
      - name: different-service
        image: payalsasmal/ubuntu_18.04:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
          name: ubuntu

---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-service
  labels:
    app: ubuntu-service
spec:
  ports:
    - port: 4000
      targetPort: 4000
  selector:
      app: ubuntu-deploy
  type: LoadBalancer